# Generated by Django 4.2.16 on 2026-03-17 22:56

import apps.users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID — used as the external identifier in all APIs.', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='E.164 format, e.g. +260971234567. Must be a valid MTN or Airtel Zambia number.', max_length=15, unique=True, validators=[apps.users.validators.ZambianPhoneValidator()])),
                ('email', models.EmailField(blank=True, default='', help_text='Optional. Used for transactional emails only — not for login.', max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BUYER', 'Buyer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], db_index=True, default='BUYER', max_length=10)),
                ('nrc_number', models.CharField(blank=True, help_text='Zambian NRC format: XXXXXX/XX/X (e.g. 123456/78/1). Unique per user. Required for KYC verification.', max_length=20, null=True, unique=True, validators=[apps.users.validators.ZambianNRCValidator()])),
                ('kyc_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=12)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when KYC documents were last submitted.', null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when KYC was last reviewed by an admin.', null=True)),
                ('kyc_rejection_reason', models.TextField(blank=True, default='', help_text='Mandatory when kyc_status = REJECTED. Shown to user.')),
                ('nrc_front_key', models.CharField(blank=True, default='', help_text='S3/R2 object key for NRC front image. Never expose as public URL.', max_length=512)),
                ('nrc_back_key', models.CharField(blank=True, default='', help_text='S3/R2 object key for NRC back image.', max_length=512)),
                ('selfie_key', models.CharField(blank=True, default='', help_text='S3/R2 object key for liveness selfie image.', max_length=512)),
                ('physical_address', models.TextField(blank=True, default='', help_text='Physical address in Zambia. Required for KYC completion. BoZ mandates collection and retention.')),
                ('province', models.CharField(blank=True, default='', help_text='Zambian province (e.g. Copperbelt, Lusaka).', max_length=50)),
                ('is_frozen', models.BooleanField(db_index=True, default=False, help_text='True when account is frozen by fraud system or admin. Frozen users cannot initiate transactions.')),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.TextField(blank=True, default='')),
                ('device_fingerprint', models.CharField(blank=True, default='', help_text='Latest device fingerprint hash from FingerprintJS (Phase 2).', max_length=256)),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='Timestamp when user explicitly accepted Terms of Service and Privacy Policy. Required under Zambia Data Protection Act 2021.', null=True)),
                ('data_deletion_requested_at', models.DateTimeField(blank=True, help_text='Set when user exercises right to erasure. Triggers anonymisation workflow within 30 days (DPA 2021 s.72).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates admin panel access. Does not imply ADMIN role.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False, help_text='True after OTP verification on registration.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('kyc_reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who performed the last KYC review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['kyc_status', 'role'], name='idx_user_kyc_role'), models.Index(fields=['is_frozen'], name='idx_user_frozen'), models.Index(fields=['nrc_number'], name='idx_user_nrc')],
            },
        ),
    ]
