# Generated by Django 4.2.16 on 2026-05-28 18:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "orders",
            "0002_rename_orders_order_buyer_status_idx_orders_orde_buyer_i_4389c9_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("NEW_ACCOUNT_HIGH_VALUE", "New Account + High Value Order"),
                            ("IP_BLACKLIST", "IP Address Blacklisted"),
                            ("PAYMENT_VELOCITY", "Payment Attempt Velocity"),
                            ("ADDRESS_MISMATCH", "Shipping Address Mismatch"),
                            ("ORDER_VELOCITY", "Order Placement Velocity"),
                            ("PAYMENT_METHOD_NEW", "New Payment Method + High Value"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("account_age_days_threshold", models.PositiveIntegerField(default=7)),
                (
                    "order_value_threshold_zmw",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=12
                    ),
                ),
                ("payment_attempts_window_minutes", models.PositiveIntegerField(default=10)),
                ("payment_attempts_count_threshold", models.PositiveIntegerField(default=3)),
                ("order_velocity_window_minutes", models.PositiveIntegerField(default=60)),
                ("order_velocity_count_threshold", models.PositiveIntegerField(default=3)),
                ("payment_method_age_hours_threshold", models.PositiveIntegerField(default=24)),
                ("address_mismatch_account_age_days", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fraud Rule",
                "verbose_name_plural": "Fraud Rules",
                "db_table": "fraud_rule",
            },
        ),
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True, unique=True)),
                ("reason", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("cloudflare_synced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blacklisted_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Blacklist Entry",
                "verbose_name_plural": "IP Blacklist",
                "db_table": "fraud_ip_blacklist",
            },
        ),
        migrations.CreateModel(
            name="FraudEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rule_triggered",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW_ACCOUNT_HIGH_VALUE", "New Account + High Value Order"),
                            ("IP_BLACKLIST", "IP Address Blacklisted"),
                            ("PAYMENT_VELOCITY", "Payment Attempt Velocity"),
                            ("ADDRESS_MISMATCH", "Shipping Address Mismatch"),
                            ("ORDER_VELOCITY", "Order Placement Velocity"),
                            ("PAYMENT_METHOD_NEW", "New Payment Method + High Value"),
                        ],
                        help_text="Empty when event represents ML verdict rather than a specific rule.",
                        max_length=40,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("FLAGGED", "Flagged — Review Required"),
                            ("CLEARED", "Cleared — No Fraud Signals"),
                            ("FROZEN", "Frozen — Manual Review Mandatory"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ml_risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="XGBoost risk score 0.0–1.0. Null if ML scoring not yet active.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ml_freeze_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Threshold at time of scoring — captures config at decision time.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "feature_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="All ML features at time of scoring. Immutable after creation.",
                    ),
                ),
                (
                    "shap_values",
                    models.JSONField(
                        default=dict,
                        help_text="SHAP values per feature for compliance explainability.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "outcome_confirmed_fraud",
                    models.BooleanField(
                        blank=True,
                        help_text="Set post-resolution: True=confirmed fraud, False=false positive, None=pending.",
                        null=True,
                    ),
                ),
                ("outcome_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fraud_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Event",
                "verbose_name_plural": "Fraud Events",
                "db_table": "fraud_event",
                "indexes": [
                    models.Index(
                        fields=["order", "evaluated_at"], name="fraud_event_order_i_6bc136_idx"
                    ),
                    models.Index(
                        fields=["verdict", "evaluated_at"], name="fraud_event_verdict_282c17_idx"
                    ),
                    models.Index(fields=["rule_triggered"], name="fraud_event_rule_tr_dedac5_idx"),
                ],
            },
        ),
    ]
