# Generated by Django 4.2.16 on 2026-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowaccount",
            name="state",
            field=models.CharField(
                choices=[
                    ("FROZEN", "FROZEN"),
                    ("DELIVERED", "DELIVERED"),
                    ("PENDING", "PENDING"),
                    ("RELEASED", "RELEASED"),
                    ("REFUNDED", "REFUNDED"),
                    ("HELD", "HELD"),
                    ("DISPUTED", "DISPUTED"),
                    ("IN_TRANSIT", "IN_TRANSIT"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
