# Generated by Django 4.2.16 on 2026-05-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "orders",
            "0002_rename_orders_order_buyer_status_idx_orders_orde_buyer_i_4389c9_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tracking_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public token for unauthenticated tracking page. Never expose the PK.",
                        unique=True,
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("DHL", "DHL Zambia"),
                            ("FEDEX", "FedEx"),
                            ("ZAMPOST", "Zampost"),
                            ("GENERIC", "Generic / Manual Carrier"),
                            ("INTERNAL", "Internal Warehouse Transfer"),
                        ],
                        db_index=True,
                        default="GENERIC",
                        max_length=20,
                    ),
                ),
                (
                    "carrier_tracking_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Carrier-assigned tracking reference (e.g. DHL waybill number).",
                        max_length=100,
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("AIR", "Air Freight (5-10 days)"),
                            ("SEA", "Sea Freight (35-45 days)"),
                            ("EXPRESS", "Express Courier"),
                            ("ROAD", "Road Freight (SADC)"),
                        ],
                        default="AIR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created — Awaiting Dispatch"),
                            ("DISPATCHED", "Dispatched from Origin"),
                            ("IN_TRANSIT", "In Transit (International)"),
                            ("CUSTOMS", "At Zambia Customs (ZRA / ASYCUDA)"),
                            ("CLEARED", "Customs Cleared"),
                            ("OUT_FOR_DELIVERY", "Out for Last-Mile Delivery"),
                            ("DELIVERED", "Delivered to Buyer"),
                            ("FAILED_DELIVERY", "Delivery Attempt Failed"),
                            ("RETURNED", "Returned to Sender"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=25,
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        default="CN",
                        help_text="ISO 3166-1 alpha-2 country code (e.g. CN, ZM, ZA).",
                        max_length=2,
                    ),
                ),
                ("origin_address", models.TextField(blank=True)),
                ("destination_country", models.CharField(default="ZM", max_length=2)),
                ("destination_address", models.TextField(blank=True)),
                (
                    "freight_forwarder",
                    models.CharField(
                        blank=True,
                        help_text="Freight forwarder company name handling international leg.",
                        max_length=120,
                    ),
                ),
                (
                    "customs_agent",
                    models.CharField(
                        blank=True,
                        help_text="ZRA-licensed clearing agent handling ASYCUDA submission.",
                        max_length=120,
                    ),
                ),
                (
                    "last_mile_courier",
                    models.CharField(
                        blank=True,
                        help_text="Lusaka last-mile courier (e.g. DHL Zambia, Zampost).",
                        max_length=120,
                    ),
                ),
                (
                    "warehouse_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when goods arrived at Lusaka bonded warehouse.",
                        null=True,
                    ),
                ),
                (
                    "warehouse_dispatched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when goods left Lusaka warehouse for last-mile.",
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "volume_cbm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cubic metres — used for freight cost calculation.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "declared_value_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Declared customs value in USD for ZRA duty calculation.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "duty_paid_zmw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual import duty paid in ZMW.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("commercial_invoice_key", models.CharField(blank=True, max_length=500)),
                ("packing_list_key", models.CharField(blank=True, max_length=500)),
                ("bill_of_lading_key", models.CharField(blank=True, max_length=500)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual delivery timestamp. Set when status moves to DELIVERED.",
                        null=True,
                    ),
                ),
                (
                    "delivery_confirmed_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUYER", "Buyer Confirmed"),
                            ("CARRIER", "Carrier Confirmed"),
                            ("AUTO", "Auto-Confirmed (Timeout)"),
                            ("ADMIN", "Admin Confirmed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "last_carrier_poll_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time Celery polled the carrier API for status updates.",
                        null=True,
                    ),
                ),
                (
                    "carrier_api_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error response from carrier API — for debugging.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Vendor or admin who created this shipment record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_shipment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created — Awaiting Dispatch"),
                            ("DISPATCHED", "Dispatched from Origin"),
                            ("IN_TRANSIT", "In Transit (International)"),
                            ("CUSTOMS", "At Zambia Customs (ZRA / ASYCUDA)"),
                            ("CLEARED", "Customs Cleared"),
                            ("OUT_FOR_DELIVERY", "Out for Last-Mile Delivery"),
                            ("DELIVERED", "Delivered to Buyer"),
                            ("FAILED_DELIVERY", "Delivery Attempt Failed"),
                            ("RETURNED", "Returned to Sender"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location description (e.g. 'Kenneth Kaunda Int. Airport, Lusaka').",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable event description — shown on buyer tracking page."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CARRIER_WEBHOOK", "Carrier Webhook (Push)"),
                            ("CARRIER_POLL", "Carrier API Poll (Pull)"),
                            ("VENDOR_MANUAL", "Vendor Manual Update"),
                            ("ADMIN_MANUAL", "Admin Manual Update"),
                            ("SYSTEM", "System (Auto-Confirm / Timeout)"),
                        ],
                        default="SYSTEM",
                        max_length=25,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Raw JSON response from carrier API or webhook — never displayed publicly.",
                        null=True,
                    ),
                ),
                (
                    "event_timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp as reported by carrier. Use this for display, not created_at.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "event_timestamp"],
                        name="logistics_t_shipmen_3fb086_idx",
                    ),
                    models.Index(fields=["status"], name="logistics_t_status_737fc5_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="logistics_s_status_2d3ba5_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["carrier", "carrier_tracking_number"], name="logistics_s_carrier_c698dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["tracking_token"], name="logistics_s_trackin_f5a25f_idx"),
        ),
    ]
