# Generated by Django 4.2.16 on 2026-05-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "orders",
            "0002_rename_orders_order_buyer_status_idx_orders_orde_buyer_i_4389c9_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("escrow", "0002_alter_escrowaccount_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ITEM_NOT_RECEIVED", "Item Not Received"),
                            ("ITEM_NOT_AS_DESCRIBED", "Item Not as Described"),
                            ("ITEM_DAMAGED", "Item Arrived Damaged"),
                            ("WRONG_ITEM", "Wrong Item Sent"),
                            ("PARTIAL_DELIVERY", "Partial Delivery"),
                            ("SELLER_UNRESPONSIVE", "Seller Unresponsive"),
                            ("OTHER", "Other — See Description"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — Awaiting Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED_BUYER", "Resolved — Buyer Favour"),
                            ("RESOLVED_VENDOR", "Resolved — Vendor Favour"),
                            ("RESOLVED_SPLIT", "Resolved — Split Decision"),
                            ("WITHDRAWN", "Withdrawn by Buyer"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ZMW amount refunded to buyer. Null until resolved.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        help_text="Admin must resolve by this datetime (72h default)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Support agent assigned to review this dispute.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escrow_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute",
                        to="escrow.escrowaccount",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute",
                        to="orders.order",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "submitted_by_role",
                    models.CharField(
                        choices=[("BUYER", "Buyer"), ("VENDOR", "Vendor"), ("ADMIN", "Admin")],
                        max_length=10,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Document (PDF/Word)"),
                            ("TEXT", "Written Statement"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Stored in S3/R2. Null for TEXT type.",
                        null=True,
                        upload_to="disputes/evidence/%Y/%m/",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Written statement or caption for file evidence."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "submitted_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("before_status", models.CharField(blank=True, max_length=20)),
                ("after_status", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="disputes.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "created_at"], name="disputes_di_status_edf3a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["assigned_to", "status"], name="disputes_di_assigne_eb5d18_idx"
            ),
        ),
    ]
