import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuthStore, useCartStore } from "../store";
import { formatZMW } from "../utils";

const CartPage: React.FC = () => {
  const navigate = useNavigate(); const authenticated = useAuthStore((s) => s.isAuthenticated);
  const items = useCartStore((s) => s.items); const updateQuantity = useCartStore((s) => s.updateQuantity); const remove = useCartStore((s) => s.removeItem); const total = useCartStore((s) => s.totalZMW());
  if (!items.length) return <main className="mx-auto max-w-3xl px-4 py-20 text-center sm:px-6"><p className="text-5xl">♧</p><h1 className="mt-5 text-3xl font-black tracking-tight text-slate-950">Your cart is waiting.</h1><p className="mt-2 text-slate-500">Find something extraordinary to bring it to life.</p><Link to="/shop" className="mt-7 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-blue-600">Explore products</Link></main>;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><nav className="mb-7 text-sm text-slate-500"><Link to="/shop" className="hover:text-blue-600">Shop</Link><span className="px-2">/</span>Cart</nav><h1 className="mb-7 text-4xl font-black tracking-tight text-slate-950">Your cart <span className="text-slate-400">({items.length})</span></h1><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><section className="space-y-3">{items.map((item) => <article key={item.product_id} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-blue-50 to-violet-100 text-3xl text-blue-300">{item.image_url ? <img src={item.image_url} alt="" className="h-full w-full object-cover" /> : "✦"}</div><div className="flex min-w-0 flex-1 flex-col"><div className="flex justify-between gap-3"><h2 className="line-clamp-2 font-semibold text-slate-900">{item.product_name}</h2><button onClick={() => remove(item.product_id)} className="text-sm text-slate-400 hover:text-red-600" aria-label={`Remove ${item.product_name}`}>Remove</button></div><div className="mt-auto flex items-end justify-between"><div className="flex items-center rounded-lg border border-slate-200"><button onClick={() => updateQuantity(item.product_id, item.quantity - 1)} className="px-3 py-1.5 text-slate-600">−</button><span className="min-w-8 text-center text-sm font-semibold">{item.quantity}</span><button disabled={item.quantity >= item.max_stock} onClick={() => updateQuantity(item.product_id, item.quantity + 1)} className="px-3 py-1.5 text-slate-600 disabled:text-slate-300">+</button></div><p className="font-black text-slate-950">{formatZMW(Number(item.price_zmw) * item.quantity)}</p></div></div></article>)}</section><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-slate-950">Order summary</h2><div className="mt-5 space-y-3 border-y border-slate-100 py-5 text-sm text-slate-600"><p className="flex justify-between"><span>Subtotal</span><span>{formatZMW(total)}</span></p><p className="flex justify-between"><span>Delivery</span><span>Calculated at checkout</span></p></div><p className="mt-5 flex justify-between text-lg font-black text-slate-950"><span>Total</span><span>{formatZMW(total)}</span></p><button onClick={() => navigate(authenticated ? "/checkout" : "/login")} className="mt-6 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700">Secure checkout →</button><p className="mt-4 text-center text-xs text-slate-400">Protected by secure escrow payment</p></aside></div></main>;
};
export default CartPage;
