import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { platformApi, type PlatformStatus } from "../api/platform";

const fallback: PlatformStatus = { platform: "Lingi7 Control Center", api_version: "v1", authentication: { provider: "Django JWT", sso_source: "Lingi7 users", duplicate_login_systems: false }, applications: [{ id:"marketplace", name:"Marketplace", status:"integrated", api_base:"/api/v1", dashboard_path:"/shop" }, { id:"catalog", name:"Catalog enrichment", status:"service-integrated", api_base:"/api/enrichment", dashboard_path:"/vendor/products" }, { id:"assistant", name:"AI shopping assistant", status:"service-integrated", api_base:"/api/assistant", dashboard_path:"/" }], ai: { orchestrator:"Django + LangGraph", llm:"Llama 3.2", catalog_llm:"Qwen 2.5", vlm:"LLaVA", text_embeddings:"BGE Small", image_embeddings:"CLIP", vector_database:"Milvus", proprietary_model_required:false } };

const PlatformDashboardPage: React.FC = () => {
  const [status, setStatus] = useState<PlatformStatus>(fallback); const [offline, setOffline] = useState(false);
  useEffect(() => { platformApi.status().then(setStatus).catch(() => setOffline(true)); }, []);
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-[30px] bg-slate-950 px-7 py-10 text-white sm:px-10"><p className="text-sm font-bold tracking-[.16em] text-cyan-300">ADMIN CONTROL CENTER</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-4xl font-black tracking-tight">{status.platform}</h1><p className="mt-3 max-w-xl text-slate-300">Marketplace operations, catalog intelligence, and system health in one trusted workspace.</p></div><span className="w-fit rounded-full bg-emerald-400/15 px-4 py-2 text-sm font-bold text-emerald-300">● Systems operational</span></div></div>{offline && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Live status is unavailable. Showing the current integration map.</div>}<section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Services online" value={`${status.applications.length}`} detail="connected applications" /><Metric label="Authentication" value="Secure" detail={status.authentication.provider} /><Metric label="AI stack" value="Ready" detail={status.ai.orchestrator} /><Metric label="API version" value={status.api_version} detail="active platform API" /></section><section className="mt-10 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><h2 className="text-2xl font-black tracking-tight text-slate-950">Operational areas</h2><div className="mt-5 grid gap-4">{status.applications.map((app) => <Link key={app.id} to={app.dashboard_path} className="group flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-200 hover:shadow-md"><div><p className="font-bold text-slate-950">{app.name}</p><p className="mt-1 text-sm text-slate-500">{app.api_base}</p></div><div className="flex items-center gap-4"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{app.status}</span><span className="text-blue-600 transition group-hover:translate-x-1">→</span></div></Link>)}</div></div><aside className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-slate-950">Security & identity</h2><dl className="mt-5 space-y-4 text-sm"><Row label="Provider" value={status.authentication.provider} /><Row label="User source" value={status.authentication.sso_source} /><Row label="Duplicate logins" value={status.authentication.duplicate_login_systems ? "Detected" : "Not detected"} /><Row label="Proprietary AI required" value={status.ai.proprietary_model_required ? "Yes" : "No"} /></dl><div className="mt-7 rounded-xl bg-blue-50 p-4 text-sm text-blue-900"><b>Audit ready.</b> Activity, permissions, and system settings remain accessible through the established backend controls.</div></aside></section></main>;
};
const Metric = ({label, value, detail}: {label:string; value:string; detail:string}) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>;
const Row = ({label, value}: {label:string; value:string}) => <div className="flex justify-between gap-4 border-b border-slate-100 pb-3 last:border-0"><dt className="text-slate-500">{label}</dt><dd className="max-w-[58%] text-right font-semibold text-slate-900">{value}</dd></div>;
export default PlatformDashboardPage;
