import React from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { storesApi } from "../api/resources";
import { PageEmpty, PageError, PageLoading } from "../components/feedback/PageStates";
import type { PublicStore } from "../types";

export const brandTone = (name: string) => ["from-blue-600 via-cyan-500 to-violet-600", "from-violet-600 via-fuchsia-500 to-rose-500", "from-emerald-600 via-teal-500 to-cyan-500", "from-orange-500 via-amber-400 to-rose-500"][name.length % 4];
export const StoreMark = ({ store }: { store: PublicStore }) => store.logo ? <img src={store.logo} alt={`${store.name} logo`} className="h-full w-full object-cover" /> : <span>{store.name.slice(0, 2).toUpperCase()}</span>;

const ShopDirectoryPage: React.FC = () => {
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["shop-directory"], queryFn: () => storesApi.list() });
  const stores = data?.results ?? [];
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav className="mb-8 text-sm text-slate-500"><Link to="/" className="hover:text-blue-600">Home</Link><span className="px-2">/</span>Shops</nav><section className="rounded-[32px] bg-slate-950 px-6 py-12 text-white sm:px-10"><p className="text-xs font-bold tracking-[.18em] text-cyan-300">THE LINGI7 MARKETPLACE</p><h1 className="mt-3 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">Every shop has its own story.</h1><p className="mt-4 max-w-xl text-slate-300">Browse distinct merchant storefronts, then keep shopping across the entire Lingi7 marketplace whenever you want.</p><Link to="/shop" className="mt-7 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950">Shop all stores</Link></section>{isLoading ? <div className="mt-8"><PageLoading label="Finding live shops…" /></div> : isError ? <div className="mt-8"><PageError message="The store directory could not load." onRetry={() => refetch()} /></div> : stores.length === 0 ? <div className="mt-8"><PageEmpty title="No shops are live yet" description="Approved merchant storefronts will appear here as soon as they publish listings." /></div> : <section className="mt-10"><div className="mb-6 flex items-end justify-between"><div><h2 className="text-3xl font-black tracking-tight text-slate-950">Shop by store</h2><p className="mt-1 text-slate-500">Independent stores, one trusted checkout.</p></div><span className="text-sm font-semibold text-slate-500">{data?.count ?? stores.length} live shops</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{stores.map((store) => <Link key={store.slug} to={`/shops/${store.slug}`} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`h-28 bg-gradient-to-br ${brandTone(store.name)} p-5`}><span className="grid h-14 w-14 place-items-center overflow-hidden rounded-2xl bg-white/90 text-xl font-black text-slate-950 shadow-lg"><StoreMark store={store} /></span></div><div className="p-5"><h3 className="text-xl font-black text-slate-950">{store.name}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-500">{store.description || "Verified Lingi7 merchant"}</p><p className="mt-4 text-sm text-slate-500">{store.product_count} live listing{store.product_count === 1 ? "" : "s"}</p><p className="mt-5 text-sm font-bold text-blue-600">Visit storefront →</p></div></Link>)}</div></section>}</main>;
};
export default ShopDirectoryPage;
