import React, { useDeferredValue, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { productsApi, storesApi } from "../api/resources";
import { PageEmpty, PageError, PageLoading } from "../components/feedback/PageStates";
import { formatZMW } from "../utils";
import type { ProductListItem } from "../types";
import { brandTone, StoreMark } from "./ShopDirectoryPage";

const StorefrontPage: React.FC = () => {
  const { slug = "" } = useParams<{ slug: string }>();
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const store = useQuery({ queryKey: ["storefront", slug], queryFn: () => storesApi.retrieve(slug), enabled: Boolean(slug) });
  const products = useQuery({ queryKey: ["storefront-products", slug, deferredQuery], queryFn: () => productsApi.list({ page: 1, store: slug, q: deferredQuery || undefined }), enabled: Boolean(slug) });
  if (store.isLoading || products.isLoading) return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><PageLoading label="Opening this storefront…" /></main>;
  if (store.isError) return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><PageError message="This storefront is unavailable or is not approved." onRetry={() => store.refetch()} /></main>;
  const merchant = store.data!; const listings = products.data?.results ?? [];
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><nav className="mb-7 text-sm text-slate-500"><Link to="/" className="hover:text-blue-600">Home</Link><span className="px-2">/</span><Link to="/shops" className="hover:text-blue-600">Shops</Link><span className="px-2">/</span>{merchant.name}</nav><section className={`overflow-hidden rounded-[32px] bg-gradient-to-br ${brandTone(merchant.name)} text-white`}>{merchant.banner && <div className="h-40 bg-cover bg-center sm:h-52" style={{ backgroundImage: `url(${merchant.banner})` }} />}<div className="p-6 sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-5"><span className="grid h-20 w-20 place-items-center overflow-hidden rounded-3xl bg-white text-2xl font-black text-slate-950 shadow-xl"><StoreMark store={merchant} /></span><div><p className="text-xs font-bold tracking-[.18em] text-white/70">VERIFIED LINGI7 STORE</p><h1 className="mt-2 text-4xl font-black tracking-tight">{merchant.name}</h1><p className="mt-2 max-w-xl text-sm text-white/80">{merchant.description || "A distinct storefront on Lingi7, with one secure marketplace checkout."}</p></div></div><Link to="/shop" className="rounded-xl bg-white px-4 py-2.5 text-center text-sm font-bold text-slate-950">Explore all shops</Link></div></div></section>{products.isError ? <div className="mt-8"><PageError message="This store profile loaded, but its products could not be retrieved." onRetry={() => products.refetch()} /></div> : <section className="mt-10"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-3xl font-black tracking-tight text-slate-950">From {merchant.name}</h2><p className="mt-1 text-slate-500">{products.data?.count ?? listings.length} products in this store only</p></div><label className="flex w-full max-w-sm items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><span className="text-slate-400">Search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${merchant.name}`} aria-label={`Search ${merchant.name}`} className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label></div>{listings.length === 0 ? <PageEmpty title={query ? "No matches in this store" : "No live products in this shop"} description={query ? "Try another term. Your search is limited to this merchant's products." : "This merchant may be preparing their next collection. Explore the central marketplace in the meantime."} action={<Link to="/shop" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Browse marketplace</Link>} /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{listings.map((product) => <StoreProductCard key={product.id} product={product} />)}</div>}</section>}</main>;
};
const StoreProductCard = ({ product }: { product: ProductListItem }) => <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><Link to={`/products/${product.slug}`} className="grid aspect-square place-items-center bg-gradient-to-br from-blue-50 via-white to-violet-100">{product.primary_image_url ? <img src={product.primary_image_url} alt={product.name} loading="lazy" className="h-full w-full object-cover" /> : <span className="text-6xl text-blue-300">✦</span>}</Link><div className="p-4"><p className="text-xs text-slate-400">{product.category_name}</p><Link to={`/products/${product.slug}`}><h2 className="mt-1 line-clamp-2 font-semibold text-slate-900">{product.name}</h2></Link><div className="mt-4 flex items-center justify-between"><span className="font-black text-slate-950">{formatZMW(product.price_zmw)}</span><span className={`text-xs font-bold ${product.in_stock ? "text-emerald-600" : "text-red-600"}`}>{product.in_stock ? "In stock" : "Sold out"}</span></div></div></article>;
export default StorefrontPage;
