# Generated by Django 4.2.16 on 2026-05-28 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("PUSH", "Push Notification")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_CONFIRMED", "Order Confirmed"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("PAYMENT_SUCCESS", "Payment Successful"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PAYMENT_RECEIPT", "Payment Receipt"),
                            ("ESCROW_HELD", "Escrow Held"),
                            ("ESCROW_RELEASED", "Escrow Released — Payout Sent"),
                            ("ESCROW_DISPUTED", "Escrow Disputed"),
                            ("ESCROW_REFUNDED", "Escrow Refunded"),
                            ("ESCROW_FROZEN", "Escrow Frozen — Review Required"),
                            ("ORDER_SHIPPED", "Order Shipped"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("ORDER_AUTO_CONFIRMED", "Order Auto-Confirmed"),
                            ("DISPUTE_OPENED", "Dispute Opened"),
                            ("DISPUTE_RESOLVED", "Dispute Resolved"),
                            ("DISPUTE_EVIDENCE_REQUESTED", "Evidence Requested"),
                            ("STORE_APPROVED", "Store Approved"),
                            ("STORE_REJECTED", "Store Rejected"),
                            ("STORE_SUSPENDED", "Store Suspended"),
                            ("LISTING_APPROVED", "Product Listing Approved"),
                            ("LISTING_REJECTED", "Product Listing Rejected"),
                            ("KYC_APPROVED", "KYC Approved"),
                            ("KYC_REJECTED", "KYC Rejected"),
                            ("KYC_REMINDER", "KYC Submission Reminder"),
                            ("WELCOME", "Welcome to Lingi7"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("LOGIN_OTP", "Login OTP"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(
                        help_text="Resolved email or phone at dispatch time. Immutable after creation.",
                        max_length=320,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body_plain", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of template context variables at time of dispatch.",
                    ),
                ),
                ("related_object_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("related_object_type", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "event_type", "status"],
                        name="notificatio_recipie_d68696_idx",
                    ),
                    models.Index(
                        fields=["channel", "status", "created_at"],
                        name="notificatio_channel_7124d7_idx",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="notificatio_related_df6367_idx",
                    ),
                ],
            },
        ),
    ]
