# Generated by Django 4.2.16 on 2026-05-28 09:39

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_buyer_i_4389c9_idx",
            old_name="orders_order_buyer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_seller__c90b9c_idx",
            old_name="orders_order_seller_status_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_orde_status_25e057_idx",
            old_name="orders_order_status_created_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(
                db_index=True,
                default=apps.orders.models._order_ref,
                help_text="Human-readable order reference shown to buyers/sellers.",
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="raised_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_disputes_raised",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="reason",
            field=models.CharField(
                choices=[
                    ("ITEM_NOT_RECEIVED", "Item Not Received"),
                    ("ITEM_NOT_AS_DESCRIBED", "Item Not As Described"),
                    ("WRONG_ITEM", "Wrong Item Sent"),
                    ("DAMAGED_ITEM", "Item Arrived Damaged"),
                    ("SELLER_UNRESPONSIVE", "Seller Unresponsive"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REFUND_BUYER", "Full Refund to Buyer"),
                    ("RELEASE_SELLER", "Release Funds to Seller"),
                    ("PARTIAL_REFUND", "Partial Refund"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_disputes_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("DISPUTED", "Disputed"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("DISPUTED", "Disputed"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                max_length=20,
            ),
        ),
    ]
