import React, { useEffect, useState } from "react";
import { Bell, ChevronDown, Heart, Menu, Moon, Search, ShoppingBag, Sun, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuthStore, useCartStore } from "../../store";

const iconButton = "relative grid h-10 w-10 place-items-center rounded-xl text-slate-600 transition hover:bg-slate-100 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white";
const choices = { language: ["EN", "BM", "NY"], currency: ["ZMW", "USD", "ZAR"] };

const TopBar: React.FC = () => {
  const navigate = useNavigate(); const totalItems = useCartStore((s) => s.totalItems()); const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const [open, setOpen] = useState(false); const [dark, setDark] = useState(false); const [menu, setMenu] = useState<"language" | "currency" | null>(null); const [language, setLanguage] = useState("EN"); const [currency, setCurrency] = useState("ZMW");
  useEffect(() => { const enabled = localStorage.getItem("lingi7-theme") === "dark"; setDark(enabled); document.documentElement.classList.toggle("dark", enabled); setLanguage(localStorage.getItem("lingi7-language") || "EN"); setCurrency(localStorage.getItem("lingi7-currency") || "ZMW"); }, []);
  const toggleTheme = () => { const enabled = !dark; setDark(enabled); localStorage.setItem("lingi7-theme", enabled ? "dark" : "light"); document.documentElement.classList.toggle("dark", enabled); };
  const choose = (kind: "language" | "currency", value: string) => { if (kind === "language") { setLanguage(value); localStorage.setItem("lingi7-language", value); } else { setCurrency(value); localStorage.setItem("lingi7-currency", value); } setMenu(null); };
  const selector = (kind: "language" | "currency", value: string) => <div className="relative hidden sm:block"><button onClick={() => setMenu(menu === kind ? null : kind)} aria-expanded={menu === kind} className="flex items-center gap-1 rounded-lg px-2 py-2 text-sm font-medium text-slate-600 dark:text-slate-300">{value}<ChevronDown size={14} /></button>{menu === kind && <div className="absolute right-0 mt-2 min-w-24 overflow-hidden rounded-xl border border-slate-200 bg-white p-1 shadow-xl dark:border-slate-700 dark:bg-slate-900">{choices[kind].map((option) => <button key={option} onClick={() => choose(kind, option)} className={`block w-full rounded-lg px-3 py-2 text-left text-sm font-semibold ${option === value ? "bg-blue-50 text-blue-700 dark:bg-blue-950" : "text-slate-600 hover:bg-slate-50 dark:text-slate-200 dark:hover:bg-slate-800"}`}>{option}</button>)}</div>}</div>;
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-3 sm:px-6 lg:px-8"><Link to="/" className="shrink-0 text-xl font-black tracking-[-.08em] text-slate-950 dark:text-white" aria-label="Lingi7 home">LINGI<span className="text-blue-600">7</span></Link><nav className="hidden items-center gap-6 text-sm font-semibold text-slate-600 dark:text-slate-300 lg:flex"><Link to="/shop">Shop</Link><Link to="/shop">Categories</Link><Link to="/shop">Deals</Link><Link to="/shop">New in</Link></nav><button onClick={() => navigate("/shop")} className="hidden min-w-0 flex-1 items-center gap-2 rounded-xl bg-slate-100 px-4 py-2.5 text-left text-sm text-slate-400 dark:bg-slate-900 md:flex"><Search size={16} /><span>Search anything</span><kbd className="ml-auto rounded border border-slate-200 bg-white px-1.5 py-0.5 text-[10px] dark:border-slate-700 dark:bg-slate-800">Cmd K</kbd></button><div className="ml-auto flex items-center gap-1">{selector("language", language)}{selector("currency", currency)}<button onClick={toggleTheme} aria-label={dark ? "Use light theme" : "Use dark theme"} aria-pressed={dark} className={iconButton}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button onClick={() => navigate("/notifications")} aria-label="Notifications" className={`${iconButton} hidden sm:grid`}><Bell size={19} /></button><button onClick={() => navigate("/wishlist")} aria-label="Wishlist" className={`${iconButton} hidden sm:grid`}><Heart size={19} /></button><button onClick={() => navigate(isAuthenticated ? "/account" : "/login")} aria-label="Account" className={iconButton}><UserRound size={19} /></button><button onClick={() => navigate("/cart")} aria-label="Cart" className={iconButton}><ShoppingBag size={19} />{totalItems > 0 && <span className="absolute right-0 top-0 grid h-4 w-4 place-items-center rounded-full bg-blue-600 text-[9px] font-bold text-white">{totalItems > 9 ? "9+" : totalItems}</span>}</button><button onClick={() => setOpen((value) => !value)} className={`${iconButton} lg:hidden`} aria-expanded={open} aria-label="Menu"><Menu size={20} /></button></div></div>{open && <nav className="border-t border-slate-100 px-4 py-3 dark:border-slate-800 lg:hidden"><div className="mx-auto flex max-w-7xl flex-wrap gap-4 text-sm font-semibold text-slate-600 dark:text-slate-300"><Link to="/shop">Shop</Link><Link to="/shop">Categories</Link><Link to="/shop">Deals</Link><Link to="/vendor">Become a seller</Link></div></nav>}</header>;
};
export default TopBar;
