# Generated by Django 4.2.16 on 2026-03-22 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='UTC timestamp.  Never update this field.'),
        ),
    ]
