# Generated by Django 4.2.16 on 2026-05-28 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key per payment attempt. Prevents duplicate API calls on retries. Format: {direction}-{escrow_account_id}-{attempt_number}",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="FK to orders.Order — stored as UUID to avoid circular app dependency.",
                    ),
                ),
                (
                    "escrow_account_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="FK to escrow.EscrowAccount — loose coupling by design.",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MTN_MOMO", "MTN Mobile Money"), ("AIRTEL", "Airtel Money")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Collection (buyer pays)"),
                            ("DISBURSEMENT", "Disbursement (vendor payout)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated — API call sent"),
                            ("PENDING", "Pending — awaiting provider confirmation"),
                            ("SUCCESS", "Success — confirmed by provider"),
                            ("FAILED", "Failed — provider rejected"),
                            ("TIMEOUT", "Timeout — no response within SLA"),
                            ("CANCELLED", "Cancelled — voided before completion"),
                        ],
                        db_index=True,
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="Provider-assigned transaction reference (e.g. MTN financialTransactionId).",
                        max_length=255,
                    ),
                ),
                (
                    "provider_response_code",
                    models.CharField(
                        blank=True,
                        help_text="Raw provider response/error code for debugging.",
                        max_length=50,
                    ),
                ),
                (
                    "provider_response_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full provider API response stored for audit and debugging.",
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True,
                        help_text="MSISDN of the payer (collection) or recipient (disbursement).",
                        max_length=20,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1-indexed retry count. Max 3 per business rules."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When provider confirmed final SUCCESS or FAILED status.",
                        null=True,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the payment (null for system-initiated).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Attempt",
                "verbose_name_plural": "Payment Attempts",
                "db_table": "payments_payment_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MTN_MOMO", "MTN Mobile Money"), ("AIRTEL", "Airtel Money")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Provider event type (e.g. 'SUCCESSFUL', 'FAILED').",
                        max_length=100,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        db_index=True,
                        help_text="The provider's unique identifier for this event. Used as idempotency key — duplicate references are rejected.",
                        max_length=255,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        default=dict,
                        help_text="Sanitised request headers (Authorization stripped).",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full raw webhook payload as received."
                    ),
                ),
                (
                    "signature_valid",
                    models.BooleanField(
                        default=False,
                        help_text="True if X-Callback-Token or equivalent header validated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received — queued for processing"),
                            ("PROCESSED", "Processed — escrow updated"),
                            ("DUPLICATE", "Duplicate — already processed"),
                            ("INVALID", "Invalid — signature or payload validation failed"),
                            ("ERROR", "Error — processing raised an exception"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, help_text="Exception message if status=ERROR."),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved after matching provider_reference to a PaymentAttempt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "payments_webhook_event",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "status"], name="payments_we_provide_063413_idx"
                    ),
                    models.Index(fields=["received_at"], name="payments_we_receive_1da9bd_idx"),
                ],
                "unique_together": {("provider", "provider_reference")},
            },
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["order_id", "direction"], name="payments_pa_order_i_2d668a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["provider", "status"], name="payments_pa_provide_ec71b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["provider_reference"], name="payments_pa_provide_722c15_idx"
            ),
        ),
    ]
