# Generated by Django 4.2.16 on 2026-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_alter_escrowaccount_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowaccount',
            name='state',
            field=models.CharField(choices=[('FROZEN', 'FROZEN'), ('DISPUTED', 'DISPUTED'), ('REFUNDED', 'REFUNDED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('RELEASED', 'RELEASED'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED'), ('HELD', 'HELD')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
