# Generated by Django 4.2.16 on 2026-06-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_alter_escrowaccount_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowaccount',
            name='state',
            field=models.CharField(choices=[('HELD', 'HELD'), ('REFUNDED', 'REFUNDED'), ('FROZEN', 'FROZEN'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('RELEASED', 'RELEASED'), ('DISPUTED', 'DISPUTED'), ('PENDING', 'PENDING')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
